access_key_name:
  in: path
  name: access_key
  description: The name of your access key.
  required: true
  schema:
    type: string
  example: DOACCESSKEYEXAMPLE

sort:
  in: query
  name: sort
  required: false
  description: The field to sort by.
  schema:
    type: string
    default: "created_at"
  example: created_at

sort_direction:
  in: query
  name: sort_direction
  required: false
  description: The direction to sort by.
  schema:
    type: string
    default: "desc"
  example: desc

name:
  in: query
  name: name
  required: false
  description: The name of the access key.
  schema:
    type: string
    default: ""
  example: my-access-key

bucket:
  in: query
  name: bucket
  required: false
  description: The name of the bucket.
  schema:
    type: string
    default: ""
  example: my-bucket

permission:
  in: query
  name: permission
  required: false
  description: The permission of the access key.
  schema:
    type: string
    default: ""
  example: read
